default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: eugene_mindscape_development
  username: omwomo97
  password: Omwomo97

test:
  <<: *default
  database: eugene_mindscape_test
  username: omwomo97
  password: Omwomo97

production:
  <<: *default
  database: eugene_mindscape_production
  username: omwomo97
  password: Omwomo97
